syntax = "proto3";

package rental;

service RentalAccommodationService {
    rpc add_property (AddPropertyRequest) returns (AddPropertyResponse);
    rpc create_users (stream UserProfile) returns (CreateUsersResponse);
    rpc update_property (UpdatePropertyRequest) returns (UpdatePropertyResponse);
    rpc remove_property (RemovePropertyRequest) returns (RemovePropertyResponse);
    rpc list_available_properties (ListAvailablePropertiesRequest) returns (stream Property);
    rpc search_property (SearchPropertyRequest) returns (SearchPropertyResponse);
    rpc book_property (BookPropertyRequest) returns (BookPropertyResponse);
    rpc confirm_booking (ConfirmBookingRequest) returns (ConfirmBookingResponse);
}

message Property {
    string property_id = 1;
    string name = 2;
    string location = 3;
    string property_type = 4;
    double price_per_night = 5;
    string status = 6;
}

message AddPropertyRequest {
    string name = 1;
    string location = 2;
    string property_type = 3;
    double price_per_night = 4;
    string status = 5;
}

message AddPropertyResponse {
    string property_id = 1;
}

message UserProfile {
    string user_id = 1;
    string name = 2;
    string role = 3;
}

message CreateUsersResponse {
    int32 users_created = 1;
    string message = 2;
}

message UpdatePropertyRequest {
    string property_id = 1;
    string name = 2;
    string location = 3;
    string property_type = 4;
    double price_per_night = 5;
    string status = 6;
}

message UpdatePropertyResponse {
    Property property = 1;
}

message RemovePropertyRequest {
    string property_id = 1;
}

message RemovePropertyResponse {
    repeated Property available_properties = 1;
}

message ListAvailablePropertiesRequest {
    string location = 1;
    double min_price = 2;
    double max_price = 3;
}

message SearchPropertyRequest {
    string property_id = 1;
}

message SearchPropertyResponse {
    bool available = 1;
    string status_message = 2;
    Property property = 3;
}

message BookPropertyRequest {
    string guest_id = 1;
    string property_id = 2;
    string check_in_date = 3;
    string check_out_date = 4;
}

message BookPropertyResponse {
    bool success = 1;
    string message = 2;
}

message ConfirmBookingRequest {
    string guest_id = 1;
}

message ConfirmBookingResponse {
    bool success = 1;
    string message = 2;
    string property_id = 3;
    string check_in_date = 4;
    string check_out_date = 5;
    int32 number_of_nights = 6;
    double total_cost = 7;
}